### ISSUE TITLE
Documentation questions...

### ISSUE THREAD

**Issue by richb-hanover** [AOHUA/redux-state-sync#11]
This package looks pretty slick. A couple questions about how to use it.

1. Does redux-state-sync use localStorage? If so, does this mean it will persist between browser sessions? (That could be helpful.)

2. If it uses localStorage, is it subject to the same ~5mbyte limit? What happens if the app runs over that limit?

3. I believe the way to test the example code is `cd example; yarn install; yarn start` That opens a window that has a to-do app. Opening another tab to the same URL and entering a to-do also shows it in the original window. Correct? 

4. The 'init new tab with current state' feature includes two code snippets. I am unsure how to incorporate them into the example project to verify its operation.

Thanks for any help!

**Comment by LeHoanVu** [comment]
I also have a project that is wanting to update data between tabs in the browser. If this tab changes then the other tab must change accordingly. I'm wanting to use your library to write redux-state-sync. But I finished reading the document does not know how to use this library.Look soon you give examples so I can understand how to use this package .. Thank you AOHUA

**Comment by AOHUA** [comment]
@LeHoanVu hi than you for being interested in redux-state-sync. Apologize for the confusing documentation. But I have already created an example using create react app, redux and redux-state-sync. If you still don't understand how to use it, welcome to raise any issues. Thank you.

**Comment by AOHUA** [comment]
@richb-hanover @LeHoanVu Sorry for the typo, usinh my phone to reply.

**Comment by richb-hanover** [comment]
> hi, I appreciate that you have raised this questions, however I can only give you a detailed reply on next Monday or Tuesday.

Thanks for the speedy acknowledgement. I'll watch for your response.

**Comment by LeHoanVu** [comment]
I would like to thank AOHUA very much. i will try to re-read your documentation to try .. thank you ..!

**Comment by AOHUA** [comment]
@LeHoanVu Hey. You can check the master branch code. It has a folder called "example".

**Comment by AOHUA** [comment]
@richb-hanover I will answer your question respectively.

1. Yes. Redux-state-sync uses localStorage and the storage event to keep state sync across browser tabs. But it doesn't persist your state in the localStorage. The only thing it does is that it sends the same action that the active tab sends out and the new feature that I build is used to init new tab with your existing tab's state.

2. Yes, it subjects the same limit as localStorage. This is the reason why the new feature is an experimental feature, in case someone got a very large state which is over 5MB or 10MB. Also, localStorage's API are all synchronous, if the state is very large, it may cause the page not responding.

3. Correct, but you can also try the new feature. Open the todo app and add one todo, then open another todo app, it should have the same todo which is created on your first tab. 

For the example project, I actually disabled one action, you can change this line in the /src/index.js,createStorageListener(store, { initiateWithState: true, predicate: actionType => actionType !== 'TOGGLE_TODO' }). By removing the predicate, it will send all the actions that sent out in the active tab.

4. The example is already enabled the new feature. Firstly you need to set the 'initiateWithState' to true in the config. Then you need to wrap your root reducer, you can check this file in the example: /reducers/index.js

Thank you again for your questions. I will find some time to rewrite the documentation. ;-)

**Comment by richb-hanover** [comment]
This is helpful. I have been tweaking the docs locally. Let me tweak a bit more, and then I'll send a PR. Thanks!
