### ISSUE TITLE
No guard against bad data in local storage

### ISSUE THREAD

**Issue by riquier** [AOHUA/redux-state-sync#12]
Every time an action is fired, all recieving tabs get either of the following console errors:

### Error 2
![screen shot 2018-05-11 at 2 07 28 pm](https://user-images.githubusercontent.com/10848273/39906942-c1251302-5524-11e8-9bde-8dc2f8f5e24b.png)

### Error 2
<img width="351" alt="screen shot 2018-05-11 at 2 07 35 pm" src="https://user-images.githubusercontent.com/10848273/39906943-c154f3b0-5524-11e8-94df-58559ded199b.png">

Please note we are using the `predicate` option

**Comment by riquier** [comment]
@AOHUA thank you very much were are using **0.1.0** however I have now upgraded to **1.1.0** and are still getting a very similar error.

Screenshot from 1.1.0
<img width="543" alt="screen shot 2018-05-14 at 10 26 58 am" src="https://user-images.githubusercontent.com/10848273/39973640-5e4b81aa-5761-11e8-9795-42aaedb910bd.png">

**Comment by AOHUA** [comment]
@riquier I just checked the example inside this repo. It doesn't throw any error. I feel that maybe you are using the storage event in other places as well? However, I can add a try-catch block here, to prevent the parse error. Btw in your case, Is redux-state-sync still working properly?

**Comment by riquier** [comment]
@AOHUA I will verify it soon, but for reference `redux-state-sync` appears to function correctly even with the error

**Comment by riquier** [comment]
@AOHUA I can confirm that fixes the issue and looking at your change I suspect it was occuring because we were writing to storage for other purposes as well. Thank you very much
