### ISSUE TITLE
Actions are duplicated in same window when we use IE

### ISSUE THREAD

**Issue by npaulo** [AOHUA/redux-state-sync#15]
## Problem
IE has a special behavior with storage event, when we call `localStorage.setItem(...)` the current `window ` receives the storage event and dispatch again the same action.
More information in this link [ie-localstorage-event-misfired](https://stackoverflow.com/questions/18476564/ie-localstorage-event-misfired)

### My solution idea:
- Create a unique id for each window when the listener is created;
- Add that window unique id to each action;
- Inside the listener verify if  window unique id is equals to the received action, if is equal discard that action;

**Comment by AOHUA** [comment]
Thank you for reporting this bug. Your solution sounds good to me. I will find some time to work on that. You can also send a pull request if you want to do it.

**Comment by npaulo** [comment]
Hello @AOHUA,
I made a pull request let me know if you agree with my changes.
