### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by AntonioMendez** [AOHUA/redux-state-sync#17]
Hello there,

I have been using your middleware (which I think is amazing!) lately in a Typescript project and I found some minor issues. When I tried to import something from it, I got the following warning:

```
[ts]

Could not find a declaration file for module 'redux-state-sync' [...] implicitly has an 'any' type.
Try 'npm install @types/redux-state-sync' [...]
```

Then, I tried the following as suggested:

```
npm install @types/redux-state-sync
```

but I got this other error:

```
npm ERR! code E404
npm ERR! 404 Not Found: @types/redux-state-sync@latest
```

At this point, I realized there is no type declarations file (not in your project, nor in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped#readme)). So I decided to create one and I would like to share it with you: 

``` typescript
// Type definitions for redux-state-sync 2.0
// Project: https://github.com/AOHUA/redux-state-sync#readme
// Definitions by: AntonioMendez <https://github.com/AntonioMendez>
// TypeScript Version: 2.9.2

import { Store, Reducer, Middleware, Action, AnyAction } from 'redux'
import BroadcastChannel from 'broadcast-channel'

interface IStampedAction {
    $uuid: string
    $wuid: string
}

type StampedAction = AnyAction & IStampedAction
type MiddlewareConfig = {
    channel?: string,
    predicate?: Function | null
    blacklist?: Array<string>
    whitelist?: Array<string>
    broadcastChannelOption?: object | null
}
type MessageListenerConfig = {
    channel: BroadcastChannel
    dispatch: (action: AnyAction | StampedAction) => void
    allowed: (type?: string) => boolean
}

// S: state object type
export function initStateWithPrevTab<S> (
    store: Store<S>
): Store<S>

// S: state object type
export function withReduxStateSync<S> (
    appReducer: Reducer<S>
): (state: any, action: AnyAction) => Reducer<S>

export function createStateSyncMiddleware (config?: MiddlewareConfig): Middleware

// export for test
export function generateUuidForAction (action: AnyAction): StampedAction
// export for test
export function isActionAllowed (config: MiddlewareConfig): (type?: any) => boolean
// export for test
export function createMessageListener (config: MessageListenerConfig): void
```

I have been using this file in my own project and it works smoothly (no errors, no warnings), but I am not 100% sure the definitions are correct. Of course, feel free to make any change you wish and I hope this helps.

Thank you!.

**Comment by AOHUA** [comment]
Cool, let me try to add TypeScript support ASAP, most probably during weekend. If you need it urgently, you can submit a pull request.

**Comment by AOHUA** [comment]
I finally added types to DefinitelyTyped, Thank you @AntonioMendez, you can check the types [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e6e55443f88128b6393105407c8e8239cb10509b/types/redux-state-sync/index.d.ts)
