### ISSUE TITLE
Sagas

### ISSUE THREAD

**Issue by jaulz** [AOHUA/redux-state-sync#46]
Is there any recommended way to use it with `redux-saga`? Currently, if actions are replicated to another tab the sagas will also fire and load/update data again. It would be great to sync only the state itself and not the actions. Or do I misunderstand anything here? Thanks anyway for the great library!

**Comment by AOHUA** [comment]
You can add those action names in the blacklist. please refer to the doc.

**Comment by jaulz** [comment]
If I do that the state won't be updated. I mean what the library currently does is that it syncs actions but not the state. Is there any specific reason why you chose this approach? Maybe I missed something...

**Comment by AOHUA** [comment]
Could you give an example of your use case? I believe that if you are using saga to handle the side effects, you should have one action to trigger the saga(e.g. GET_USER_REQUEST) and after saga resolved the side effects, it will trigger another action with the results to update the state(e.g. GET_USER_SUCCESS). So what you can do is to add the first action into the blacklist.

**Comment by jaulz** [comment]
In theory I could maintain every single action in the whitelist but at some point it will be unmaintainable. I use a meta property in the original action that will then trigger a `*_REQUEST` function (depending on whether the user has a connection or not). Thus, I cannot simply filter for the suffix. 

I just raised two PRs which should allow this kind of behaviour in combination with `redux-saga`:
https://github.com/AOHUA/redux-state-sync/pull/47
https://github.com/AOHUA/redux-state-sync/pull/48

Please let me know what you think and if I should change anything.
